"""Build the RISC-V firmware with clang and turn it into a flat binary image.

The SoC's register map lives in :mod:`xsynth.hdl.soc`. The C header the firmware
compiles against is generated from those constants rather than checked in, so
the two cannot drift apart.

The toolchain is the LLVM one that is already on the system (``clang`` with the
``riscv32`` target, ``ld.lld`` and ``llvm-objcopy``). There is no custom backend
and no fork: the firmware's two trips into the co-processor are inline asm.
"""

from __future__ import annotations

import shutil
import subprocess
import tempfile
from pathlib import Path

from xsynth.hdl.soc import (
    MMIO_BASE,
    REG_COMMANDS,
    REG_CONTROL,
    REG_COUNTER,
    REG_RX_DATA,
    REG_RX_STATUS,
    REG_SAMPLES,
    REG_STATUS,
)
from xsynth.hdl.voice import VOICES
from xsynth.protocol import (
    OP_CLEAR_SCHEDULE,
    OP_NOTE_OFF,
    OP_NOTE_ON,
    OP_RESET,
    OP_SCHEDULE_AT,
    OP_SET_AMP,
    OP_SET_ATTACK,
    OP_SET_DECAY,
    OP_SET_FREQ,
    OP_SET_MASTER,
    OP_SET_RELEASE,
    OP_SET_SUSTAIN,
    OP_SET_WAVE,
    PKT_COMMANDS,
    SCHEDULE_ENTRIES,
    VOICE_ANY,
)

SW_DIR = Path(__file__).resolve().parent / "sw"

TARGET = "riscv32-unknown-elf"
MARCH = "rv32i"
MABI = "ilp32"

SOURCES = ("start.S", "main.c", "control.c")
LINKER_SCRIPT = "link.ld"
REGISTER_HEADER = "registers.h"
PROTOCOL_HEADER = "protocol.h"

# Written to REG_STATUS once at boot: the host reads it to tell "a program is
# running" from "a program is running and it is the one I uploaded".
FIRMWARE_MAGIC = 0x5853_594E  # "XSYN"

# Name and MMIO offset of every register the firmware may touch.
REGISTERS = (
    ("REG_STATUS", REG_STATUS),
    ("REG_COUNTER", REG_COUNTER),
    ("REG_CONTROL", REG_CONTROL),
    ("REG_SAMPLES", REG_SAMPLES),
    ("REG_RX_DATA", REG_RX_DATA),
    ("REG_RX_STATUS", REG_RX_STATUS),
    ("REG_COMMANDS", REG_COMMANDS),
)

# Protocol constants the firmware needs, generated for the same reason.
CONSTANTS = (
    ("PKT_COMMANDS", PKT_COMMANDS),
    ("FIRMWARE_MAGIC", FIRMWARE_MAGIC),
)

# What the command word means, for the code that has to take one apart. The
# voice count belongs here rather than with the register map because the voice
# field is part of that word.
COMMAND_CONSTANTS = (
    ("VOICE_COUNT", VOICES),
    ("VOICE_ANY", VOICE_ANY),
    ("OP_NOTE_ON", OP_NOTE_ON),
    ("OP_NOTE_OFF", OP_NOTE_OFF),
    ("OP_SET_FREQ", OP_SET_FREQ),
    ("OP_SET_WAVE", OP_SET_WAVE),
    ("OP_SET_AMP", OP_SET_AMP),
    ("OP_RESET", OP_RESET),
    ("OP_SET_ATTACK", OP_SET_ATTACK),
    ("OP_SET_DECAY", OP_SET_DECAY),
    ("OP_SET_SUSTAIN", OP_SET_SUSTAIN),
    ("OP_SET_RELEASE", OP_SET_RELEASE),
    ("OP_SET_MASTER", OP_SET_MASTER),
    ("OP_SCHEDULE_AT", OP_SCHEDULE_AT),
    ("OP_CLEAR_SCHEDULE", OP_CLEAR_SCHEDULE),
    ("SCHEDULE_ENTRIES", SCHEDULE_ENTRIES),
)


def register_header() -> str:
    """The MMIO definitions, generated so they match the hardware."""
    defines = "\n".join(
        f"#define {name}  (*(volatile unsigned *){MMIO_BASE + offset:#010x})"
        for name, offset in REGISTERS
    )
    constants = "\n".join(
        f"#define {name}  {value:#04x}" for name, value in CONSTANTS
    )
    return (
        "/* Generated by xsynth.firmware from xsynth.hdl.soc; do not edit. */\n"
        "\n"
        "#ifndef XSYNTH_REGISTERS_H\n"
        "#define XSYNTH_REGISTERS_H\n"
        "\n"
        f"{defines}\n"
        "\n"
        f"{constants}\n"
        "\n"
        "#endif\n"
    )


def protocol_header() -> str:
    """The command word's vocabulary, generated so it matches the host's.

    Kept apart from :func:`register_header` because it is not about registers:
    :mod:`xsynth.sw.control` includes this and no MMIO at all, which is what
    lets the allocator and the schedule be compiled for the host and tested
    there.
    """
    constants = "\n".join(
        f"#define {name}  {value:#04x}" for name, value in COMMAND_CONSTANTS
    )
    return (
        "/* Generated by xsynth.firmware from xsynth.protocol; do not edit. */\n"
        "\n"
        "#ifndef XSYNTH_PROTOCOL_H\n"
        "#define XSYNTH_PROTOCOL_H\n"
        "\n"
        f"{constants}\n"
        "\n"
        "#endif\n"
    )


def _tool(name: str) -> str:
    path = shutil.which(name)
    if path is None:
        raise RuntimeError(
            f"{name} is not on the PATH; the firmware needs clang, ld.lld and "
            f"llvm-objcopy with the riscv32 target"
        )
    return path


def _run(command: list[str]) -> None:
    result = subprocess.run(command, capture_output=True, text=True)
    if result.returncode:
        raise RuntimeError(
            "the firmware build failed:\n"
            + " ".join(command) + "\n"
            + result.stdout + result.stderr
        )


def build_firmware(*, sources=SOURCES, optimize: str = "s",
                   keep: str | None = None) -> bytes:
    """Compile the firmware and return it as a flat binary image.

    The image is what the loader writes into program memory; its first word is
    the reset vector, so it must be loaded at address 0.

    Size rather than speed, because the memory is the binding constraint: the
    schedule ring and the code share the same eight kilobytes, and `-Os` halves
    the code for a loop that still finishes in a fraction of the 560 cycles a
    48 kHz sample leaves. `-Oz` is further out than the freestanding build can
    go -- it wants a `memcpy` there is none of.
    """
    with tempfile.TemporaryDirectory() as tmp:
        root = Path(keep) if keep is not None else Path(tmp)
        root.mkdir(parents=True, exist_ok=True)

        (root / REGISTER_HEADER).write_text(register_header())
        (root / PROTOCOL_HEADER).write_text(protocol_header())

        objects = []
        for name in sources:
            obj = root / (Path(name).stem + ".o")
            _run([
                _tool("clang"),
                f"--target={TARGET}",
                f"-march={MARCH}",
                f"-mabi={MABI}",
                f"-O{optimize}",
                "-ffreestanding",
                "-nostdlib",
                "-Wall",
                "-Wextra",
                "-I", str(root),
                "-I", str(SW_DIR),
                "-c", str(SW_DIR / name),
                "-o", str(obj),
            ])
            objects.append(obj)

        elf = root / "firmware.elf"
        _run([
            _tool("ld.lld"),
            "-T", str(SW_DIR / LINKER_SCRIPT),
            "-o", str(elf),
            *[str(obj) for obj in objects],
        ])

        binary = root / "firmware.bin"
        _run([_tool("llvm-objcopy"), "-O", "binary", str(elf), str(binary)])
        return binary.read_bytes()
