"""Patches applied to the vendored hdl-util/hdmi sources at build time.

The vendored files under :mod:`xsynth.third_party.hdmi` are kept byte-for-byte
identical to upstream so that re-vendoring stays cheap. Everything Xsynth needs
to change is applied here, textually, with an assertion that each patch still
matches exactly once. If upstream changes, the assertion fires and we notice.

Patches:

1. ``packet_picker.sv`` mixes blocking and non-blocking assignment to
   ``frame_counter`` inside one ``always_ff``. Vendor tools tolerate this; the
   slang frontend rejects it. Rewritten to a semantically equivalent
   non-blocking form (the result is ``(frame_counter + 4) % 192``).

2. ``hdmi.sv`` assigns ``control_data`` with a blocking assignment in the
   reset branch and non-blocking in the else branch. Converted to non-blocking;
   the reset branch writes a constant that is not read again in the same block,
   so semantics are unchanged.
"""

from __future__ import annotations

from pathlib import Path

_HDMI_DIR = Path(__file__).resolve().parent.parent / "third_party" / "hdmi" / "src"
_SV_DIR = Path(__file__).resolve().parent.parent / "sv"

# Files read by the SystemVerilog (slang) frontend, in dependency order.
HDMI_SOURCES = [
    "tmds_channel.sv",
    "audio_clock_regeneration_packet.sv",
    "audio_info_frame.sv",
    "audio_sample_packet.sv",
    "auxiliary_video_information_info_frame.sv",
    "source_product_description_info_frame.sv",
    "packet_assembler.sv",
    "packet_picker.sv",
    "serializer.sv",
    "hdmi.sv",
]

# Xsynth-authored glue, read last.
WRAPPER_SOURCES = ["xsynth_hdmi.sv"]

_PATCHES: dict[str, list[tuple[str, str, str]]] = {
    "packet_picker.sv": [
        (
            "frame_counter blocking assignments",
            """        frame_counter = frame_counter + 8'd4;
        if (frame_counter >= 8'd192)
            frame_counter = frame_counter - 8'd192;""",
            """        if (frame_counter + 8'd4 >= 8'd192)
            frame_counter <= frame_counter + 8'd4 - 8'd192;
        else
            frame_counter <= frame_counter + 8'd4;""",
        ),
    ],
    "hdmi.sv": [
        (
            "control_data blocking assignment in reset branch",
            "                control_data = 6'd0;",
            "                control_data <= 6'd0;",
        ),
    ],
    "serializer.sv": [
        (
            "TMDS clock driven directly from clk_pixel",
            "        assign tmds_clock = clk_pixel;",
            """        // Xsynth: keep the TMDS clock on the raw pixel clock, matching the
        // known-good Tang Nano 9K designs. The serializers have a small, fixed
        // latency relative to it, which HDMI sinks tolerate.
        assign tmds_clock = clk_pixel;""",
        ),
    ],
}

# Suffix used for the generated copies. Deliberately *not* ``.sv`` so that
# Amaranth's ``iter_files(".sv")`` does not feed them to ``read_verilog -sv``,
# which cannot parse unpacked-array ports.
GENERATED_SUFFIX = ".svp"


def _patched_text(filename: str) -> str:
    text = (_HDMI_DIR / filename).read_text()
    for description, old, new in _PATCHES.get(filename, []):
        count = text.count(old)
        if count != 1:
            raise RuntimeError(
                f"hdl-util patch {filename!r} ({description}) expected exactly one "
                f"match, found {count}. Upstream may have changed; re-check "
                f"xsynth/platform/hdmi_patch.py against the vendored sources."
            )
        text = text.replace(old, new)
    return text


def build_files() -> dict[str, str]:
    """Return ``{filename_in_build_dir: contents}`` for every HDL source.

    The patched upstream sources and the Xsynth wrapper are all emitted with a
    ``.svp`` suffix. The Yosys script generated by the platform patch reads them
    with ``read_slang`` instead of ``read_verilog -sv``.
    """
    files: dict[str, str] = {}
    for name in HDMI_SOURCES:
        files[name + GENERATED_SUFFIX] = _patched_text(name)
    for name in WRAPPER_SOURCES:
        files[name + GENERATED_SUFFIX] = (_SV_DIR / name).read_text()
    return files


def build_filenames() -> list[str]:
    """Build-dir filenames of all SystemVerilog sources, in read order."""
    return [name + GENERATED_SUFFIX for name in HDMI_SOURCES + WRAPPER_SOURCES]


def slang_defines(*, video_mode, dvi_output: bool, audio_rate: int,
                  audio_bits: int) -> list[str]:
    """Preprocessor defines configuring the Xsynth HDMI wrapper.

    The wrapper cannot take module parameters because the Yosys slang frontend
    instantiates top-level modules, which strips their parameters.
    """
    return [
        "GW_IDE",
        f"XSYNTH_VIDEO_ID_CODE={video_mode.video_id_code}",
        f"XSYNTH_BIT_WIDTH={video_mode.bit_width}",
        f"XSYNTH_BIT_HEIGHT={video_mode.bit_height}",
        f"XSYNTH_DVI_OUTPUT={1 if dvi_output else 0}",
        f"XSYNTH_AUDIO_RATE={audio_rate}",
        f"XSYNTH_AUDIO_BITS={audio_bits}",
    ]
